import test from 'node:test';import assert from 'node:assert/strict';import {newStage,choose,ballValue,defaultBag} from '../game.js';import {buildDebugBag,bagRecipe} from '../debug-bag.js';
const make=()=>{const s=newStage(100);s.plainRules=true;s.items[26]='earth';s.collection.push(26);s.bag.add(26);s.nextItemId=27;s.played.push(0);return s;};
const put=(s,id,tile,value=ballValue(s,id))=>{s.stamps.add(tile);s.stampBalls[tile]=id;s.stampValues[tile]=value;s.bag.delete(id);};
const play=(s,tile)=>{s.offer=[26];s.playableSpaces=undefined;s.destinations={26:tile};return choose(s,26,tile,()=>0);};
test('Earth scores before gravity and again for a new line after falling',()=>{const s=make();for(let n=1;n<=4;n++)put(s,n,n);const r=play(s,5);assert.equal(r.points,20);assert.deepEqual(r.timeline.map(p=>p.kind),['score','gravity','score']);assert.deepEqual(s.scoredLines,['row-1','row-5']);assert.deepEqual(s.stampBalls,{21:1,22:2,23:3,24:4,25:26});assert.equal(s.calls,16);assert.equal(s.stampValues[25],0);});
test('gravity preserves order, values and identities, moves ordinary special items, and leaves ink anchored',()=>{const s=make();s.items[27]='moon';s.collection.push(27);s.nextItemId=28;put(s,1,1,-3);put(s,27,11,10);put(s,2,21,9);s.tileStamps={1:['copier'],16:['plus10']};const r=play(s,6);assert.deepEqual(s.stampBalls,{6:1,11:26,16:27,21:2});assert.equal(s.stampValues[6],-3);assert.equal(new Set(Object.values(s.stampBalls)).size,4);assert.deepEqual(s.tileStamps,{1:['copier'],16:['plus10']});assert.equal(s.collection.length,27);assert.equal(r.points,0);const next=newStage(101,5,{}, {},[],s);assert.equal(next.stampBalls[16],undefined);assert.ok(next.bag.has(27));});
test('pre-fall scoring resolves copier and trash before gravity, landing ink applies on scoring only',()=>{const s=make();for(let n=1;n<=4;n++)put(s,n,n);s.tileStamps={1:['copier'],2:['trash'],21:['plus10']};const r=play(s,5);assert.equal(r.points,10);assert.equal(s.collection.includes(2),false);assert.equal(s.bag.has(27),true);assert.equal(s.stampBalls[21],1);assert.equal(s.stampBalls[22],undefined);assert.equal(r.timeline.find(p=>p.kind==='gravity').moves.length,4);});
test('a new composition in a previously scored column pays without overlapping',()=>{const s=make();for(const [id,tile] of [[1,1],[2,6],[3,11],[4,16]])put(s,id,tile);s.scoredLines=['column-1'];const r=play(s,21);assert.equal(r.points,10);assert.equal(r.timeline.find(p=>p.kind==='gravity').moves.length,0);assert.equal(s.stamps.size,5);});
test('Earth survives debug recipes, copies its starting value and is in default testing bags',()=>{const inv=buildDebugBag([{type:'earth',value:0,count:2}]);const s=newStage(1,5,{}, {},[],inv);assert.equal(ballValue(s,26),0);assert.deepEqual(bagRecipe(s),[{type:'earth',value:0,count:2}]);assert.equal(Object.values(defaultBag().items).filter(t=>t==='earth').length,5);});
