import test from 'node:test';import assert from 'node:assert/strict';import {newStage,deal,choose,redraw} from '../game.js';
const make=()=>{const s=newStage(20);s.plainRules=true;s.offer=[1,2,3];s.destinations={1:13,2:13,3:13};return s;};
test('playing each slot replaces only that slot and spends one play',()=>{for(const slot of [0,1,2]){const s=make(),old=[...s.offer],n=old[slot];choose(s,n,13,()=>.5);old.forEach((id,i)=>{if(i!==slot)assert.equal(s.offer[i],id);});assert.notEqual(s.offer[slot],n);assert.equal(s.stampBalls[13],n);assert.equal(s.calls,16);assert.equal(s.passes,10);assert.equal(s.offer.length,3);assert.equal(new Set(s.offer).size,3);assert.equal(new Set(Object.values(s.destinations)).size,1);assert.ok(!Object.values(s.destinations).includes(13));}});
test('passing any slot preserves held balls, board and plays, returns discard to bag, and changes location',()=>{for(const slot of [0,1,2]){const s=make(),old=[...s.offer],n=old[slot];assert.ok(redraw(s,()=>.5,n));old.forEach((id,i)=>{if(i!==slot)assert.equal(s.offer[i],id);});assert.notEqual(s.offer[slot],n);assert.ok(s.bag.has(n));assert.equal(s.stamps.size,0);assert.equal(s.calls,17);assert.equal(s.passes,9);assert.equal(new Set(Object.values(s.destinations)).size,1);assert.ok(!Object.values(s.destinations).includes(13));}});
test('no passes and invalid selections leave state untouched',()=>{const s=make();s.passes=0;const before=JSON.stringify(s);assert.equal(redraw(s,()=>0,2),false);assert.equal(JSON.stringify(s),before);s.passes=1;assert.equal(redraw(s,()=>0,24),false);assert.equal(s.passes,1);});
test('Question Mark cannot consume another held ball',()=>{const s=make();s.items[26]='question';s.collection.push(26);s.bag.add(26);s.offer=[1,26,3];s.destinations={1:13,26:13,3:13};const r=choose(s,26,13,()=>0);assert.equal(r.mimic,null);assert.ok(s.bag.has(1)&&s.bag.has(3));assert.equal(s.offer[0],1);assert.equal(s.offer[2],3);});
test('small bags provide unique remaining choices, including last-square and pass fallback',()=>{const s=make();s.bag=new Set([1,2,3]);redraw(s,()=>0,2);assert.deepEqual(s.offer,[1,2,3]);choose(s,2,undefined,()=>0);assert.deepEqual(s.offer,[1,3]);assert.equal(new Set(Object.values(s.destinations)).size,1);s.bag=new Set([1]);s.offer=[];deal(s,()=>0);assert.deepEqual(s.offer,[1]);assert.ok(redraw(s,()=>0,1));});
test('zero-value King replaces only itself and spends one play',()=>{const s=make();s.items[2]='king';choose(s,2,13,()=>0);assert.equal(s.calls,16);assert.equal(s.offer[0],1);assert.equal(s.offer[2],3);});
test('stamps keep shared targets compatible with the four-stamp limit',()=>{const s=make();s.items[2]='copier';for(let tile=1;tile<=25;tile++)s.tileStamps[tile]=['x2','x2','x2','x2'];s.tileStamps[7]=[];deal(s,()=>0);assert.deepEqual(Object.values(s.destinations),[7,7,7]);});
