import test from 'node:test';import assert from 'node:assert/strict';import {newStage,choose,ballValue,MOON_PATTERNS,MARS_PATTERNS,planetPairMatches,shopItemTypes} from '../game.js';
const make=()=>{const s=newStage(100);s.plainRules=true;add(s,'moon');return s;};
function add(s,type,value){const id=s.nextItemId++;s.items[id]=type;s.collection.push(id);s.bag.add(id);s.played[id]=0;if(value!==undefined)s.ballValues[id]=value;return id;}
const put=(s,id,tile,value=ballValue(s,id))=>{s.stamps.add(tile);s.stampBalls[tile]=id;s.stampValues[tile]=value;s.bag.delete(id);};
const play=(s,id,tile)=>{s.offer=[id];s.destinations={[id]:tile};return choose(s,id,tile,()=>0);};
const phases=r=>r.timeline.filter(p=>p.scoringGroups?.[0]?.type==='moon');
test('all adjacent pairs and directional trios are unique and bounded',()=>{assert.equal(MOON_PATTERNS.length,40);assert.equal(MARS_PATTERNS.length,48);for(const list of [MOON_PATTERNS,MARS_PATTERNS]){assert.equal(new Set(list.map(p=>p.tiles.join())).size,list.length);assert.ok(list.every(p=>p.tiles.every(t=>t>=1&&t<=25)));}});
test('Moon scores matching number pairs for 112 in both orthogonal directions',()=>{for(const tiles of [[1,2],[1,6]]){const s=make();put(s,26,25);put(s,6,tiles[0]);s.ballValues[7]=6;assert.equal(play(s,7,tiles[1]).points,112);assert.equal(play(s,20,20).points,0);}});
test('Moon in bag has no effect; placing it leaves existing pairs unscored',()=>{const s=make();put(s,6,1);s.ballValues[7]=6;assert.equal(play(s,7,2).points,0);put(s,8,3,6);const r=play(s,26,25);assert.deepEqual(phases(r).map(p=>p.points),[]);assert.equal(play(s,20,20).points,0);});
test('Moon ignores special items even with identical types or values',()=>{for(const type of ['seed','d20','king','statue','earth','doubleball']){const s=make(),a=add(s,type),b=add(s,type);put(s,a,1,3);put(s,b,2,3);assert.equal(planetPairMatches(s,[1,2]),false);assert.equal(play(s,26,25).points,0);}});
test('destroying Moon disables matching pairs immediately',()=>{const s=make();put(s,26,25);const melt=add(s,'potionMelt');play(s,melt,25);put(s,6,1);s.ballValues[7]=6;assert.equal(play(s,7,2).points,0);});
test('Mars scores diagonals but Moon only scores orthogonal neighbors',()=>{const s=make(),mars=add(s,'mars');put(s,26,21);put(s,mars,25);put(s,1,1,6);put(s,2,7,6);const r=play(s,6,13);assert.equal(phases(r).reduce((a,p)=>a+p.points,0),0);assert.equal(r.timeline.filter(p=>p.scoringGroups?.[0]?.type==='mars').reduce((a,p)=>a+p.points,0),118);assert.equal(r.points,118);});
test('two identical x2 potions really apply twice and copies preserve both',()=>{const s=make();put(s,26,25);put(s,6,1);play(s,add(s,'potion2'),1);play(s,add(s,'potion2'),1);assert.deepEqual(s.itemEffects[6],['potion2','potion2']);const copy=play(s,add(s,'potionCopy'),1).copies[0].id;assert.deepEqual(s.itemEffects[copy],['potion2','potion2']);s.ballValues[7]=6;const r=play(s,7,2);assert.equal(r.points,112*4);assert.equal(phases(r)[0].activations.at(-1).groupEnd.factor,4);});
test('Moon is a zero-star shop item and new rounds reset pair history',()=>{const s=make();assert.equal(ballValue(s,26),0);assert.ok(shopItemTypes().includes('moon'));s.scoredLines=['moon-dr-1'];assert.deepEqual(newStage(101,5,{}, {},[],s).scoredLines,[]);});
