import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const fixture=sessionStorage.getItem('fixture');if(fixture){localStorage.setItem('binglatro.run.v1',fixture);sessionStorage.removeItem('fixture');}});
const url=process.env.GAME_URL||'http://localhost:5173';
const layout=()=>page.locator('#board .cell span').allTextContents().then(a=>a.map(Number));
const ready=()=>page.locator('#balls .ball:not([disabled])').first().waitFor();
const restore=async(s)=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),s);await page.reload();await page.locator('#play-button').click();};
await page.goto(url);await page.locator('#play-button').click();await ready();
const first=await layout(),ordered=Array.from({length:25},(_,i)=>i+1);assert.deepEqual([...first].sort((a,b)=>a-b),ordered);assert.notDeepEqual(first,ordered);
await page.locator('#redraw').click();await ready();assert.deepEqual(await layout(),first);
await page.locator('#pause-button').click();await page.locator('#main-menu-button').click();await page.reload();await page.locator('#play-button').click();await ready();assert.deepEqual(await layout(),first);
const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));
const row=first.slice(0,5);s.stamps=row.slice(0,4);s.bag=s.bag.filter(n=>!s.stamps.includes(n));s.stamps.forEach(n=>s.played[n]=1);s.calls=8;s.offer=[row[4]];s.paints={[row[0]]:'red',[row[1]]:'gold',[row[2]]:'blue'};
await restore(s);await ready();assert.deepEqual(await layout(),first);await page.screenshot({path:'/tmp/binglatro-shuffled.png'});
const ball=await page.locator('#balls .ball').boundingBox(),board=await page.locator('#board').boundingBox();
await page.mouse.move(ball.x+ball.width/2,ball.y+ball.height/2);await page.mouse.down();await page.mouse.move(board.x+board.width/2,board.y+board.height/2,{steps:15});await page.mouse.up();
await page.locator('.pattern-multiplier').waitFor({state:'visible'});assert.deepEqual(await page.locator('.cell.multiplied').evaluateAll(c=>c.map(n=>Number(n.id.replace('cell-','')))),row);
assert.ok(await page.locator(`#cell-${row[4]}`).evaluate(c=>c.classList.contains('stamped')));
await page.locator('#shop-screen').waitFor({state:'visible'});assert.equal(await page.locator('#score').textContent(),String(2*row.reduce((sum,n)=>sum+n,0)));assert.equal(await page.locator('.cell.stamped').count(),0);
await page.locator('#shop-next').click();await ready();const second=await layout();assert.notDeepEqual(second,first);assert.deepEqual([...second].sort((a,b)=>a-b),ordered);
assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')).paints),s.paints);
await page.locator('#pause-button').click();await page.locator('#restart-button').click();await page.locator('#confirm-restart').click();await ready();assert.notDeepEqual(await layout(),second);
// Saves from before this feature keep their old board until the next stage.
const legacy=await page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));delete legacy.board;
await restore(legacy);await ready();assert.deepEqual(await layout(),ordered);
legacy.board=Array(25).fill(1);await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),legacy);await page.reload();assert.ok((await page.locator('#play-button').textContent()).includes('PLAY'));
assert.deepEqual(errors,[]);await browser.close();console.log('Passed shuffled run/stage layouts, redraw and resume stability, position-based scoring/animations, paint persistence, restart shuffle, legacy saves and invalid-board recovery.');
