import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage} from '../game.js';import {checkShopLayout} from './shop-layout.mjs';
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:process.env.REAL_MOTION?'no-preference':'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const s=sessionStorage.getItem('fixture');if(s){localStorage.setItem('binglatro.run.v1',s);sessionStorage.removeItem('fixture');}window.events=[];const animate=Element.prototype.animate;Element.prototype.animate=function(f,o){if(this.matches('.joker-card.scoring-card'))window.events.push({id:this.dataset.joker,payout:this.dataset.payout});return animate.call(this,f,o);};});
 await page.goto(process.env.GAME_URL||'http://localhost:5173');const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1'))),ready=()=>page.locator('#balls .ball:not([disabled])').first().waitFor();const restore=async s=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),{...s,stamps:[...s.stamps],bag:[...s.bag]});await page.reload();await page.locator('#play-button').click();};
 const s=newStage(10,5,{}, {},['bingo','face-value','encore:1']);for(let n=1;n<5;n++){s.stamps.add(n);s.stampBalls[n]=n;s.stampValues[n]=n;s.bag.delete(n);}s.offer=[5];s.destinations={5:5};await restore(s);await ready();
 const card=id=>page.locator(`[data-joker="${id}"]`);const a=await card('encore:1').boundingBox(),b=await card('bingo').boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+3,b.y+b.height/2,{steps:12});await page.mouse.up();await page.waitForTimeout(250);assert.deepEqual((await read()).jokers,['encore:1','bingo','face-value']);await page.reload();await page.locator('#play-button').click();await ready();assert.equal(await page.locator('#joker-rack .joker-card').first().getAttribute('data-joker'),'encore:1');
 await card('encore:1').focus();await page.keyboard.press('ArrowRight');assert.deepEqual((await read()).jokers,['bingo','encore:1','face-value']);await page.screenshot({path:'/tmp/binglatro-encore.png'});await page.locator('#balls .ball').focus();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelector('#score').textContent==='30'&&document.querySelector('#balls .ball:not([disabled])'));
 const events=await page.evaluate(()=>window.events);assert.equal(events.filter(e=>e.id==='encore:1'&&e.payout==='AGAIN').length,5);assert.equal(events.filter(e=>e.id==='face-value').length,10);assert.equal(events[0].id,'bingo');
 await restore({...s,jokers:['encore:1','bingo','face-value']});await ready();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelector('#score').textContent==='30'&&document.querySelector('#balls .ball:not([disabled])'));assert.deepEqual((await page.evaluate(()=>window.events)).slice(0,2).map(e=>e.payout),['AGAIN','SCORE 5']);
 await card('encore:1').focus();await page.keyboard.press('Delete');assert.ok(!(await read()).jokers.includes('encore:1'));
 const shop=newStage();shop.status='passed';shop.bonusPaid=true;await restore(shop);await page.locator('#shop-screen').waitFor({state:'visible'});await checkShopLayout(page,'encore-shop');await page.locator('#shop-encore').click();assert.ok((await read()).jokers.includes('encore:1'));assert.equal((await read()).money,5);assert.ok(await page.locator('#shop-encore').isDisabled());assert.deepEqual(errors,[]);console.log('Passed drag/keyboard reorder, saved order, Encore group/points animations, removal, responsive shop and free purchase.');
}finally{await browser.close();}
