import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage,openShop,buyItem} from '../game.js';
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:process.env.REAL_MOTION?'no-preference':'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{
  const fixture=sessionStorage.getItem('fixture');if(fixture){localStorage.setItem('binglatro.run.v1',fixture);sessionStorage.removeItem('fixture');}
  window.effectEvents=[];const animate=Element.prototype.animate;
  Element.prototype.animate=function(frames,options){
   if(this.matches('.effect-source'))window.effectEvents.push({type:'source',before:document.querySelector('#cell-12 span').textContent});
   if(this.matches('.value-changing span')&&this.parentNode.dataset.valueAfter!==undefined)window.effectEvents.push({type:'change',tile:this.parentNode.id,value:this.textContent});
   if(this.matches('.joker-card.scoring-card'))window.effectEvents.push({type:'score',id:this.dataset.joker,payout:this.dataset.payout,effects:!!document.querySelector('.value-effects'),values:[8,12,14,18].map(t=>document.querySelector(`#cell-${t} span`).textContent)});
   return animate.call(this,frames,options);
  };
 });
 await page.goto(process.env.GAME_URL||'http://localhost:5173');const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));
 const restore=async s=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),{...s,stamps:[...s.stamps],bag:[...s.bag]});await page.reload();await page.locator('#play-button').click();};const ready=()=>page.locator('#balls .ball:not([disabled])').first().waitFor();
 const shop=newStage(1,0);shop.status='passed';shop.bonusPaid=true;await restore(shop);await page.locator('#shop-screen').waitFor({state:'visible'});
 assert.equal(await page.locator('#shop-shelf .shop-product').count(),7);
 for(const [width,height] of [[390,844],[320,568],[1000,800],[844,390]]){
  await page.setViewportSize({width,height});for(const sel of ['#shop-screen','#shop-shelf','#shop-next','.dashboard']){const r=await page.locator(sel).boundingBox();assert.ok(r&&r.x>=0&&r.y>=0&&r.x+r.width<=width+1&&r.y+r.height<=height+1,JSON.stringify({sel,width,height,r}));}
  assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);await page.screenshot({path:`/tmp/binglatro-shelf-${width}.png`});
 }
 await page.setViewportSize({width:390,height:844});await page.locator('#shop-shelf').evaluate(e=>e.scrollLeft=0);await page.locator('#shop-more').click();await page.locator('#shop-more').click();await page.locator('#shop-hundred').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/binglatro-shelf-hundred.png'});
 const scroll=await page.locator('#shop-shelf').evaluate(e=>e.scrollLeft);assert.ok(scroll>0);await page.locator('#shop-hundred').click();assert.equal((await read()).items[26],'hundred');assert.equal((await read()).money,0);assert.ok(Math.abs(await page.locator('#shop-shelf').evaluate(e=>e.scrollLeft)-scroll)<5);await page.locator('#shop-hundred').click();assert.equal(await page.locator('#shop-hundred-count').textContent(),'2');
 await page.locator('#shop-high-five').scrollIntoViewIfNeeded();await page.locator('#shop-high-five').click();assert.ok(await page.locator('#shop-high-five').isDisabled());assert.equal(await page.locator('#shop-shelf .shop-product').count(),7);await page.reload();await page.locator('#play-button').click();assert.ok(await page.locator('#shop-high-five').isDisabled());await page.locator('#shop-next').click();await ready();await page.locator('#bag').click();assert.equal(await page.locator('#bag-grid [data-number="26"] .face').textContent(),'100');await page.locator('#bag-dialog .close').click();
 openShop(shop);const id=buyItem(shop,'hundred'),turn=newStage(10,0,{}, {},shop.jokers,shop);[[1,11],[2,12],[3,14],[4,15],[5,8],[6,18]].forEach(([n,t])=>{turn.stamps.add(t);turn.stampBalls[t]=n;turn.stampValues[t]=n;turn.bag.delete(n);});turn.offer=[id];turn.destinations={[id]:13};await restore(turn);await ready();assert.equal(await page.locator('#balls .face').textContent(),'100');await page.locator('#balls .ball').click();assert.equal(await page.locator('#tooltip-number').textContent(),'100');assert.equal((await read()).stampValues[12],2);
 await page.keyboard.press('ArrowUp');if(process.env.REAL_MOTION){await page.locator('.effect-source').waitFor();await page.screenshot({path:'/tmp/binglatro-hundred-source.png'});await page.locator('.value-changing').first().waitFor();await page.screenshot({path:'/tmp/binglatro-hundred-changing.png'});await page.locator('[data-joker="bingo"].scoring-card').waitFor();await page.screenshot({path:'/tmp/binglatro-hundred-scoring.png'});}
 await page.waitForFunction(()=>window.effectEvents.some(e=>e.type==='score')&&!document.querySelector('.scoring-rack')&&document.querySelector('#balls .ball:not([disabled])'),null,{timeout:40000});
 const events=await page.evaluate(()=>window.effectEvents);assert.equal(events[0].type,'source');assert.equal(events[0].before,'2');assert.equal(events.filter(e=>e.type==='change').length,4);assert.equal(events.findIndex(e=>e.type==='score'),5);assert.ok(events.filter(e=>e.type==='score').every(e=>!e.effects));assert.deepEqual(events[5].values,['4','1','2','5']);assert.equal((await read()).score,108);assert.equal((await read()).stampValues[13],100);assert.equal((await read()).valueModifiers[2],-1);await page.screenshot({path:'/tmp/binglatro-hundred-finished.png'});
 await page.reload();await page.locator('#play-button').click();await ready();assert.equal((await read()).stampValues[12],1);await page.locator('#bag').click();assert.equal(await page.locator('#bag-grid [data-number="2"] .face').textContent(),'1');await page.locator('#bag-dialog .close').click();const after=await read();await restore({...after,stage:1,status:'passed',bonusPaid:true,stamps:new Set(after.stamps),bag:new Set(after.bag)});await page.locator('#shop-next').click();await ready();assert.equal((await read()).valueModifiers[2],-1);await page.locator('#bag').click();assert.equal(await page.locator('#bag-grid [data-number="2"] .face').textContent(),'1');await page.locator('#bag-dialog .close').click();
 // Negative totals, zero/negative values and signed scoring labels all survive saves.
 const negative=newStage(10,0,{}, {},['face-value','high-five:1']);negative.score=-4;negative.valueModifiers={1:-2};negative.stamps.add(13);negative.stampBalls[13]=1;negative.stampValues[13]=-1;negative.bag.delete(1);negative.offer=[2];negative.destinations={2:14};await restore(negative);await ready();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>window.effectEvents.some(e=>e.payout==='-1')&&!document.querySelector('.scoring-rack')&&document.querySelector('#balls .ball:not([disabled])'));assert.equal((await read()).score,-3);await page.reload();await page.locator('#play-button').click();await ready();assert.equal((await read()).score,-3);assert.equal(await page.locator('#score').textContent(),'-3');assert.equal(await page.locator('#progress').evaluate(e=>e.style.width),'0%');
 assert.deepEqual(errors,[]);console.log('Passed horizontal catalog, purchases, compact layouts, 100 draw, effect-before-scoring sequence, modified bag values, run/reload persistence and negative scoring.');
}finally{await browser.close();}
