import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage,ballValue,openRewardShop} from '../game.js';
const browser=await chromium.launch({channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const s=sessionStorage.getItem('fixture');if(s){localStorage.setItem('binglatro.run.v1',s);sessionStorage.removeItem('fixture');}Math.random=()=>0;window.fx=[];const original=Element.prototype.animate;Element.prototype.animate=function(f,o){if(this.matches('.king-moving'))window.fx.push('move');else if(this.matches('.king-item.drag-ghost'))window.fx.push('copy');return original.call(this,f,o);};});
 await page.goto(process.env.GAME_URL||'http://localhost:5173');
 const restore=async s=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),{...s,stamps:[...s.stamps],bag:[...s.bag]});await page.reload();await page.locator('#play-button').click();};
 const s=newStage(10);s.items[26]='king';s.items[27]='hundred';s.collection.push(26,27);s.nextItemId=28;s.bag.add(27);s.stamps.add(13);s.stampBalls[13]=26;s.stampValues[13]=10;s.tileStamps[7]=['copier','copier','x2'];s.tileMultipliers[7]=2;s.offer=[27];s.destinations={27:14};await restore(s);await page.locator('#balls .ball:not([disabled])').waitFor();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>window.fx.length===3&&document.querySelector('#balls .ball:not([disabled])'));assert.deepEqual(await page.evaluate(()=>window.fx),['move','copy','copy']);assert.equal(await page.locator('#cell-7>span').textContent(),'9');await page.screenshot({path:'/tmp/king-board.png'});let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));assert.equal(saved.items[28],'king');assert.equal(saved.valueModifiers[28],-1);await page.reload();await page.locator('#play-button').click();await page.locator('#balls .ball:not([disabled])').waitFor();assert.equal(await page.locator('#cell-7>span').textContent(),'9');
 const shop=newStage();shop.status='passed';shop.bonusPaid=true;openRewardShop(shop);shop.shopOffer.items=['king','rock'];await restore(shop);await page.locator('#shop-king').click();await page.locator('#balls .ball:not([disabled])').waitFor();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));assert.ok(Object.values(saved.items).includes('king'));assert.deepEqual(errors,[]);console.log('Verified King hop, two visible copies, Anvil value, reload and shop reward.');
}finally{await browser.close();}
