import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage} from '../game.js';
const browser=await chromium.launch({channel:'chrome'});const url=process.env.GAME_URL||'http://localhost:5174';const errors=[];
const fixture=()=>{const s=newStage(100);s.plainRules=true;for(const [id,type] of [[26,'potion20'],[27,'potion2'],[28,'potionCopy'],[29,'potionMelt']]){s.items[id]=type;s.collection.push(id);s.bag.add(id);s.played[id]=0;}s.nextItemId=30;s.stamps.add(13);s.stampBalls[13]=10;s.stampValues[13]=10;s.bag.delete(10);s.offer=[26,27,28];s.destinations={26:1,27:1,28:1};return s;};
const open=async(s,width=390)=>{const p=await browser.newPage({viewport:{width,height:width===320?568:844}});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(s=>{if(!sessionStorage.seeded){localStorage.setItem('binglatro.run.v1',JSON.stringify(s));sessionStorage.seeded='yes';}},{...s,stamps:[...s.stamps],bag:[...s.bag]});await p.goto(url);await p.locator('#play-button').click();return p;};
const ready=p=>p.waitForFunction(()=>document.querySelectorAll('#balls .ball:not([disabled])').length===3);
const read=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')));
const drop=async(p,id,tile)=>{await ready(p);const a=await p.locator(`#balls [data-number="${id}"]`).boundingBox(),b=await p.locator(`#cell-${tile}`).boundingBox();await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12});await p.mouse.up();await ready(p);};
try{for(const width of [390,320]){const p=await open(fixture(),width);await ready(p);await p.screenshot({path:`/tmp/potions-hand-${width}.png`});await drop(p,26,1);assert.equal((await read(p)).calls,17);await drop(p,26,13);assert.equal((await read(p)).calls,16);assert.ok(await p.locator('#cell-13').evaluate(c=>c.classList.contains('potion-gold')));await drop(p,27,13);assert.deepEqual((await read(p)).itemEffects[10],['potion20','potion2']);await drop(p,28,13);let s=await read(p);assert.deepEqual(s.itemEffects[30],s.itemEffects[10]);assert.ok(s.bag.includes(30));await p.locator('#cell-13').click();assert.match(await p.locator('#tooltip-potions').innerText(),/20/);assert.match(await p.locator('#tooltip-potions').innerText(),/total bingo/);await p.screenshot({path:`/tmp/potions-applied-${width}.png`});await p.reload();await p.locator('#play-button').click();await ready(p);assert.deepEqual((await read(p)).itemEffects[10],['potion20','potion2']);await p.close();}
for(const type of ['bomb','earth','d20']){const s=fixture();s.items[26]='question';s.items[27]=type;s.offer=[26];s.destinations={26:12};s.bag=new Set([26,27]);const p=await open(s);await p.locator('#balls .ball:not([disabled])').waitFor();const a=await p.locator('#balls [data-number="26"]').boundingBox();await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(a.x+a.width/2,a.y-65,{steps:8});await p.mouse.up();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('binglatro.run.v1')).calls===16);await p.locator('#balls .ball:not([disabled])').first().waitFor();const after=await read(p);if(type==='bomb'){assert.equal(after.stamps.length,0);assert.ok(!after.collection.includes(27));}if(type==='earth'){assert.equal(after.stampBalls[22],27);assert.equal(after.stampBalls[23],10);}if(type==='d20')assert.ok(after.stampValues[12]>=1&&after.stampValues[12]<=20);await p.close();}
const s=fixture();s.status='passed';s.bonusPaid=true;s.shopOffer={rewardVersion:2,items:['potion20','potionCopy','potionMelt'],claimed:false};const p=await open(s);await p.locator('#shop-potion20:not([disabled])').waitFor();await p.screenshot({path:'/tmp/potions-shop.png'});assert.equal(await p.locator('.shop-stamp-tag').first().textContent(),'POTION');await p.locator('#see-all').click();assert.equal(await p.locator('.catalog-item[data-type="copier"]').count(),0);assert.equal(await p.locator('.catalog-item[data-type^="potion"]').count(),4);await p.close();assert.deepEqual(errors,[]);console.log('Potion targeting, stacking, copying, tooltips, reload, mobile fit and shop catalog verified.');}finally{await browser.close();}
