import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage,openShop,buyItem} from '../game.js';import {checkShopLayout} from './shop-layout.mjs';
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const s=sessionStorage.getItem('fixture');if(s){localStorage.setItem('binglatro.run.v1',s);sessionStorage.removeItem('fixture');}window.rockEvents=[];const animate=Element.prototype.animate;Element.prototype.animate=function(f,o){if(this.matches('.joker-card.scoring-card'))window.rockEvents.push({id:this.dataset.joker,payout:this.dataset.payout,calls:document.querySelector('#play-count').textContent});return animate.call(this,f,o);};});
 await page.goto(process.env.GAME_URL||'http://localhost:5173');const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1'))),ready=()=>page.locator('#balls .ball:not([disabled])').first().waitFor();const restore=async s=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),{...s,stamps:[...s.stamps],bag:[...s.bag]});await page.reload();await page.locator('#play-button').click();};
 const shop=newStage(1,0);shop.status='passed';shop.bonusPaid=true;await restore(shop);await page.locator('#shop-screen').waitFor({state:'visible'});await checkShopLayout(page,'rock-shop');await page.locator('#shop-rock').click();await page.locator('#shop-rock').click();assert.equal((await read()).money,0);assert.equal(await page.locator('#shop-rock-count').textContent(),'2');await page.locator('#shop-next').click();await ready();await page.locator('#bag').click();assert.equal(await page.locator('#bag-grid .rock-item').count(),2);await page.locator('#bag-grid .rock-item').first().click();assert.equal(await page.locator('#tooltip-number').textContent(),'Rock');await page.locator('#bag-debug-toggle').click();await page.locator('#debug-clear').click();await page.locator('#debug-add').click();await page.locator('.debug-row select').selectOption('rock');assert.ok(await page.locator('.debug-row input').first().isDisabled());await page.locator('.debug-row input').nth(1).fill('3');await page.locator('#debug-apply').click();await ready();assert.match(await page.locator('#play-ball>span').textContent(),/FREE PLAY/);assert.equal(await page.locator('#balls .rock-item .face').textContent(),'');await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelectorAll('.cell.rock-item.stamped').length===1&&document.querySelector('#balls .ball:not([disabled])'));assert.equal((await read()).calls,15);assert.equal((await read()).bag.length,2);await page.locator('.cell.rock-item').click();assert.equal(await page.locator('#tooltip-number').textContent(),'Rock');await page.screenshot({path:'/tmp/binglatro-rock-board.png'});await page.reload();await page.locator('#play-button').click();await ready();assert.equal((await read()).calls,15);assert.equal(await page.locator('.cell.rock-item').count(),1);
 openShop(shop);const id=buyItem(shop,'rock'),turn=newStage(10,0,{}, {},shop.jokers,shop);turn.calls=1;[1,2,3,4].forEach(n=>{turn.stamps.add(n);turn.stampBalls[n]=n;turn.stampValues[n]=n;turn.bag.delete(n);});turn.offer=[id];turn.destinations={[id]:5};await restore(turn);await ready();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelector('#score').textContent==='10'&&document.querySelector('#balls .ball:not([disabled])'));assert.equal((await read()).calls,1);const events=await page.evaluate(()=>window.rockEvents);assert.deepEqual(events.map(e=>e.payout),['SCORE 5','+1','+2','+3','+4','+0']);assert.ok(events.every(e=>e.calls==='1'));assert.equal(await page.locator('#cell-5.rock-item').count(),1);
 await restore({...turn,stage:1,target:5,calls:15});await ready();await page.keyboard.press('ArrowUp');await page.locator('#shop-screen').waitFor({state:'visible'});assert.equal((await read()).money,15);await page.locator('#shop-next').click();await ready();assert.ok((await read()).bag.includes(id));assert.equal((await read()).calls,15);assert.deepEqual(errors,[]);console.log('Passed Rock shop/debug, numberless art/tooltip, free placement, reload, Bingo zero-point activation, last-play preservation, payout and next round.');
}finally{await browser.close();}
