import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {newStage,openShop,buyItem} from '../game.js';import {checkShopLayout} from './shop-layout.mjs';
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:process.env.REAL_MOTION?'no-preference':'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const s=sessionStorage.getItem('fixture');if(s){localStorage.setItem('binglatro.run.v1',s);sessionStorage.removeItem('fixture');}window.events=[];const animate=Element.prototype.animate;Element.prototype.animate=function(f,o){if(this.matches('.value-changing>span'))window.events.push('growth');if(this.matches('.joker-card.scoring-card'))window.events.push(this.dataset.joker);return animate.call(this,f,o);};});
 await page.goto(process.env.GAME_URL||'http://localhost:5173');const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('binglatro.run.v1'))),ready=()=>page.locator('#balls .ball:not([disabled])').first().waitFor();const restore=async s=>{await page.evaluate(s=>sessionStorage.setItem('fixture',JSON.stringify(s)),{...s,stamps:[...s.stamps],bag:[...s.bag]});await page.reload();await page.locator('#play-button').click();};
 const shop=newStage();shop.status='passed';shop.bonusPaid=true;await restore(shop);await page.locator('#shop-screen').waitFor({state:'visible'});await checkShopLayout(page,'seed-shop');await page.locator('#shop-seed').click();await page.locator('#shop-seed').click();assert.equal((await read()).money,5);assert.equal(await page.locator('#shop-seed-count').textContent(),'2');
 openShop(shop);const id=buyItem(shop,'seed'),rock=buyItem(shop,'rock'),s=newStage(10,5,{}, {},['bingo','face-value'],shop);s.offer=[id];s.destinations={[id]:1};await restore(s);await ready();assert.equal(await page.locator('#balls .seed-item .face').textContent(),'1');await page.screenshot({path:'/tmp/binglatro-seed-draw.png'});await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelector('#cell-1.seed-item')&&document.querySelector('#balls .ball:not([disabled])'));assert.equal((await read()).calls,14);assert.equal((await read()).stampValues[1],1);
 const turn={...s,stamps:new Set([1,2,3,4]),stampBalls:{1:id,2:2,3:3,4:4},stampValues:{1:1,2:2,3:3,4:4},bag:new Set(s.bag),offer:[rock],destinations:{[rock]:5}};for(const n of [id,2,3,4])turn.bag.delete(n);await restore(turn);await ready();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.querySelector('#score').textContent==='11'&&document.querySelector('#balls .ball:not([disabled])'));assert.equal((await read()).stampValues[1],2);assert.equal((await read()).calls,15);const events=await page.evaluate(()=>window.events);assert.ok(events.indexOf('growth')>=0&&events.indexOf('growth')<events.indexOf('bingo'));await page.screenshot({path:'/tmp/binglatro-seed-board.png'});await page.reload();await page.locator('#play-button').click();await ready();assert.equal(await page.locator('#cell-1>span').textContent(),'2');await page.locator('#bag').click();await page.locator('#bag-debug-toggle').click();await page.locator('#debug-clear').click();await page.locator('#debug-add').click();await page.locator('.debug-row select').selectOption('seed');assert.equal(await page.locator('.debug-row input').first().inputValue(),'1');await page.locator('.debug-row input').first().fill('8');await page.locator('#debug-apply').click();await ready();assert.equal(await page.locator('#balls .seed-item .face').textContent(),'8');assert.deepEqual(errors,[]);console.log('Passed free Seed purchases, responsive art/shop, placement, growth-before-scoring, free Rock interaction, reload and custom debug value.');
}finally{await browser.close();}
